export const SET_ERROR = 'setError'
export const PURGE_AUTH = 'logOut'
export const SET_AUTH = 'setAuth'
export const SET_USER = 'setUser'
export const GET_USER = 'getUser'
export const IS_AUTH = 'isAuth'
